/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: '設計・開発',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Architecture',
          link: { type: 'doc', id: 'architecture/index' },
          collapsed: true,
          items: [
            'architecture/layered',
            'architecture/modular-monolith',
            'architecture/onion',
            'architecture/ddd',
            'architecture/hexagonal',
            'architecture/event-driven',
            'architecture/microservices',
            'architecture/strangler-fig',
            'architecture/cqrs-event-sourcing',
            'architecture/cap-theorem',
            {
              type: 'category',
              label: 'GoF デザインパターン',
              link: { type: 'doc', id: 'architecture/design-patterns/index' },
              collapsed: true,
              items: [
                'architecture/design-patterns/creational',
                'architecture/design-patterns/structural',
                'architecture/design-patterns/behavioral',
                'architecture/design-patterns/solid',
                'architecture/design-patterns/principles',
                'architecture/design-patterns/repository',
                'architecture/design-patterns/dependency-injection',
                'architecture/design-patterns/orm-patterns',
              ],
            },
            { type: 'doc', id: 'architecture/functional-patterns/index', label: '関数型パターン' },
            {
              type: 'category',
              label: 'MV* パターン',
              link: { type: 'doc', id: 'architecture/mv-patterns/index' },
              collapsed: true,
              items: [
                'architecture/mv-patterns/mvc',
                'architecture/mv-patterns/mvp',
                'architecture/mv-patterns/mvvm',
                'architecture/mv-patterns/mvi',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Frontend',
          link: { type: 'doc', id: 'frontend/index' },
          collapsed: true,
          items: [
            'frontend/state-management',
            'frontend/reactivity',
            'frontend/js-runtime',
            'frontend/css-methodology',
            'frontend/rendering-strategy',
            'frontend/app-platform',
            'frontend/i18n',
          ],
        },
        {
          type: 'category',
          label: 'Backend',
          link: { type: 'doc', id: 'backend/index' },
          collapsed: true,
          items: [
            'backend/reverse-proxy',
            'backend/idempotency',
            'backend/caching',
            {
              type: 'category',
              label: 'API',
              link: { type: 'doc', id: 'backend/api/index' },
              collapsed: true,
              items: [
                'backend/api/rest-design',
                'backend/api/graphql',
                'backend/api/grpc',
                'backend/api/trpc',
                'backend/api/api-versioning',
                'backend/api/api-gateway',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'AI',
          link: { type: 'doc', id: 'ai/index' },
          collapsed: true,
          items: [
            'ai/overview',
            {
              type: 'category',
              label: 'LLM の基礎概念',
              link: { type: 'doc', id: 'ai/llm-basics/index' },
              collapsed: true,
              items: [
                'ai/llm-basics/hallucination',
                'ai/llm-basics/reasoning-models',
                'ai/llm-basics/context-engineering',
              ],
            },
            {
              type: 'category',
              label: 'プロンプト',
              link: { type: 'doc', id: 'ai/prompt/index' },
              collapsed: true,
              items: [
                'ai/prompt/prompt-engineering',
                'ai/prompt/prompt-injection',
              ],
            },
            {
              type: 'category',
              label: 'データ・検索',
              link: { type: 'doc', id: 'ai/data-search/index' },
              collapsed: true,
              items: [
                'ai/data-search/rag',
                'ai/data-search/embeddings',
                'ai/data-search/multimodal',
              ],
            },
            {
              type: 'category',
              label: 'エージェント',
              link: { type: 'doc', id: 'ai/agents/index' },
              collapsed: true,
              items: [
                'ai/agents/ai-agents',
                'ai/agents/mcp',
              ],
            },
            {
              type: 'category',
              label: 'モデル改善・運用',
              link: { type: 'doc', id: 'ai/mlops/index' },
              collapsed: true,
              items: [
                'ai/mlops/fine-tuning',
                'ai/mlops/evals',
                'ai/mlops/llmops',
                'ai/mlops/langfuse',
                'ai/mlops/hitl',
              ],
            },
            {
              type: 'category',
              label: '開発スタイル',
              link: { type: 'doc', id: 'ai/dev-style/index' },
              collapsed: true,
              items: [
                'ai/dev-style/ai-dlc',
                'ai/dev-style/vibe-coding',
                'ai/dev-style/harness-engineering',
              ],
            },
            {
              type: 'category',
              label: 'コンピュータビジョン',
              link: { type: 'doc', id: 'ai/computer-vision/index' },
              collapsed: true,
              items: [
                'ai/computer-vision/ocr',
                'ai/computer-vision/object-detection',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Testing',
          link: { type: 'doc', id: 'testing/index' },
          collapsed: true,
          items: [
            'testing/tdd',
            'testing/test-doubles',
            'testing/contract-testing',
            'testing/testing-strategy',
          ],
        },
        {
          type: 'category',
          label: 'Security',
          link: { type: 'doc', id: 'security/index' },
          collapsed: true,
          items: [
            'security/cors',
            'security/cookie',
            'security/encryption',
            'security/principles',
            {
              type: 'category',
              label: 'コードで防ぐ攻撃',
              link: { type: 'doc', id: 'security/code-attacks/index' },
              collapsed: true,
              items: ['security/code-attacks/web-attacks'],
            },
            {
              type: 'category',
              label: '脅威・リスク',
              link: { type: 'doc', id: 'security/threats/index' },
              collapsed: true,
              items: [
                'security/threats/zero-day',
                'security/threats/supply-chain-attack',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '認証',
          link: { type: 'doc', id: 'auth/index' },
          collapsed: true,
          items: [
            'auth/overview',
            'auth/basic-auth',
            'auth/session-auth',
            'auth/api-key',
            'auth/jwt',
            'auth/bearer',
            'auth/oauth2',
            'auth/oidc',
            'auth/saml',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '運用・インフラ',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Networking',
          link: { type: 'doc', id: 'networking/index' },
          collapsed: true,
          items: [
            'networking/osi-model',
            'networking/ip-address',
            'networking/http',
            'networking/dns',
            'networking/tls',
            'networking/realtime-protocols',
            'networking/vpc-subnet',
            'networking/nat',
            'networking/socket',
          ],
        },
        {
          type: 'category',
          label: 'Observability',
          link: { type: 'doc', id: 'observability/index' },
          collapsed: true,
          items: [
            'observability/observability-concept',
            'observability/opentelemetry',
            'observability/distributed-tracing',
            'observability/log-aggregation',
            'observability/zabbix',
            'observability/metrics-design',
          ],
        },
        {
          type: 'category',
          label: 'SRE',
          link: { type: 'doc', id: 'sre/index' },
          collapsed: true,
          items: [
            'sre/what-is-sre',
            'sre/slo-sli-sla',
            'sre/error-budget',
            {
              type: 'category',
              label: '障害パターン',
              link: { type: 'doc', id: 'sre/failure/index' },
              collapsed: true,
              items: [
                'sre/failure/single-point-of-failure',
                'sre/failure/cascade-failure',
                'sre/failure/retry-storm',
              ],
            },
            {
              type: 'category',
              label: '対策パターン',
              link: { type: 'doc', id: 'sre/resilience/index' },
              collapsed: true,
              items: [
                'sre/resilience/timeout',
                'sre/resilience/circuit-breaker',
                'sre/resilience/bulkhead',
                'sre/resilience/backpressure',
              ],
            },
            'sre/postmortem',
          ],
        },
        {
          type: 'category',
          label: 'Deployment',
          link: { type: 'doc', id: 'deployment/index' },
          collapsed: true,
          items: [
            'deployment/canary-release',
            'deployment/blue-green',
            'deployment/feature-flags',
            'deployment/edge-computing',
            'deployment/cdn',
            'deployment/gitops',
          ],
        },
        {
          type: 'category',
          label: 'Dev Tools',
          link: { type: 'doc', id: 'dev-tools/index' },
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'Infra',
              link: { type: 'doc', id: 'dev-tools/infra/index' },
              collapsed: true,
              items: [
                'dev-tools/infra/docker',
                'dev-tools/infra/podman',
                'dev-tools/infra/buildah',
                'dev-tools/infra/kubernetes',
                'dev-tools/infra/terraform',
                'dev-tools/infra/ansible',
              ],
            },
            { type: 'doc', id: 'dev-tools/platform-engineering', label: 'プラットフォームエンジニアリング' },
            {
              type: 'category',
              label: 'CI/CD',
              link: { type: 'doc', id: 'dev-tools/ci-cd/index' },
              collapsed: true,
              items: ['dev-tools/ci-cd/github-actions'],
            },
            {
              type: 'category',
              label: '環境管理',
              link: { type: 'doc', id: 'dev-tools/env-management/index' },
              collapsed: true,
              items: [
                'dev-tools/env-management/nix',
                'dev-tools/env-management/mise',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Platforms',
          link: { type: 'doc', id: 'platforms/index' },
          collapsed: true,
          items: [
            'platforms/cloud',
            'platforms/xaas',
            {
              type: 'category',
              label: 'Database',
              link: { type: 'doc', id: 'platforms/database/index' },
              collapsed: true,
              items: [
                'platforms/database/rdbms',
                'platforms/database/nosql',
                'platforms/database/newsql',
                'platforms/database/in-memory-db',
                'platforms/database/olap',
              ],
            },
            'platforms/baas',
            'platforms/kafka',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '組織・プロセス・事業',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '組織',
          link: { type: 'doc', id: 'org/index' },
          collapsed: true,
          items: [
            'org/conways-law',
            'org/silo',
            'org/devops',
            'org/team-topologies',
            'org/engineering-roles',
            'org/the-model',
          ],
        },
        {
          type: 'category',
          label: 'ビジネス',
          link: { type: 'doc', id: 'business/index' },
          collapsed: true,
          items: [
            'business/company-types',
            'business/vmv',
            'business/funding',
            'business/growth-strategy',
            'business/metrics',
            'business/north-star-metric',
            'business/kpi',
            'business/okr',
            'business/rule-of-40',
          ],
        },
        {
          type: 'category',
          label: '開発プロセス',
          link: { type: 'doc', id: 'process/index' },
          collapsed: true,
          items: [
            'process/agile',
            'process/waterfall',
            'process/shape-up',
            'process/semver',
            'process/adr',
            'process/poc',
            'process/technical-debt',
            'process/ab-testing',
            'process/git-branching',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
